# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='price',
            field=models.CharField(max_length=32),
        ),
    ]
