# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
