# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190706_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.IntegerField(choices=[(0, '无效用户'), (1, '普通用户'), (2, 'vip'), (3, 'svip')], default=1),
        ),
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserGroup'),
        ),
        migrations.AddField(
            model_name='users',
            name='roles',
            field=models.ManyToManyField(null=True, to='api.Roles'),
        ),
    ]
