# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190710_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('fanc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanc_set', to='api.Friends')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_set', to='api.Friends')),
            ],
        ),
    ]
