# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='fanc',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='focus',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
