# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190711_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='roles',
            field=models.ManyToManyField(default=1, to='api.Roles'),
        ),
    ]
