"""
Django settings for Test01 project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-o2=om3j*)r36nsez356b6^$6ks)wi9_d6$l*&a99ix1sr(k8l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'course',
    'book',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Test01.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Test01.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':"rest",
        "USER":"root",
        "PASSWORD":"123456",
        "HOST":"LOCALHOST",
        "PORT":"3306"
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR,"static")]

# 设置文件上传路径
MEDIA_ROOT=os.path.join(BASE_DIR,'static/upload_file/')


# 访问频率定义
THROTTLE_FREQUENCE=(20,3)


REST_FRAMEWORK={
    # 认证  全局的使用的认证类
    "DEFAULT_AUTHENTICATION_CLASSES":['api.utils.auth.Authentication'],
    # "UNAUTHENTICATED_USER":lambda :None,
    # 匿名用户的设置
    "UNAUTHENTICATED_USER":None,    # 匿名用户:request.user=None
    "UNAUTHENTICATED_TOKEN":None,   # 匿名用户:request.auth=None
    # 权限  全局配置权限
    # "DEFAULT_PERMISSION_CLASSES":['api.utils.permission.SVIPpermission']
    # 节流  全局配置访问控制  默认全局使用用户名进行控制频率
    "DEFAULT_THROTTLE_CLASSES":['api.utils.throttle.VisitedThrottle','api.utils.throttle.UserThrottle'],
    "DEFAULT_THROTTLE_RATES":{
        "lufei":"10/m",
        "lufei_user":"20/m"
    },
    # 版本  全局配置版本
    "DEFAULT_VERSION":'v2',   # 默认版本
    "ALLOWED_VERSIONS":['v1','v2'],    # 允许访问版本
    "VERSION_PARAM":'version',
    "DEFAULT_VERSIONING_CLASS":"rest_framework.versioning.AcceptHeaderVersioning",     # 版本信息出现在请求投中的Accept: application/json; version=1.0
    # 解析器  全局配置解析器
    "DEFAULT_PARSER_CLASSES":['rest_framework.parsers.JSONParser','rest_framework.parsers.FormParser'],
    # 分页   默认显示数据条数
    'DEFAULT_PAGINATION_CLASS':'api.utils.pagernation.MyCursorPagination',
    "PAGE_SIZE":2,
    # 渲染器   json form格式
    'DEFAULT_RENDERER_CLASSES':['rest_framework.renderers.JSONRenderer','rest_framework.renderers.BrowsableAPIRenderer'],

}

